name: Build and Upload EmuThreeDs
on:
  push:
    branches:
      - main
  pull_request:

jobs:
  build:
    name: Build and upload EmuThreeDs
    strategy:
      fail-fast: false
      matrix:
        include:
          - os: 'macos-12'
            version: '14.2'

    runs-on: ${{ matrix.os }}
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
        with:
          submodules: recursive

      # - name: Cache rust em_proxy
      #   id: cache-rust-em_proxy
      #   uses: actions/cache@v3
      #   env:
      #     cache-name: cache-rust-em_proxy
      #   with:
      #     path: ./Dependencies/em_proxy/target
      #     key: ${{ runner.os }}-build-${{ env.cache-name }}-${{ hashFiles('**/package-lock.json') }}
      #     restore-keys: |
      #       ${{ runner.os }}-build-${{ env.cache-name }}-
      #       ${{ runner.os }}-build-
      #       ${{ runner.os }}-

      - name: Install dependencies
        run: brew install ldid

      - name: Setup Xcode
        uses: maxim-lobanov/setup-xcode@v1.4.1
        with:
          xcode-version: ${{ matrix.version }}

      - name: Build EmuThreeDs
        run: |
          xcodebuild -project emuThreeDS.xcodeproj \
          -scheme emuThreeDS \
          -sdk iphoneos \
          archive -archivePath ./archive \
          CODE_SIGNING_REQUIRED=NO \
          AD_HOC_CODE_SIGNING_ALLOWED=YES \
          CODE_SIGNING_ALLOWED=NO \
          DEVELOPMENT_TEAM=XYZ0123456 \
          ORG_IDENTIFIER=com.antique \
          | xcpretty && exit ${PIPESTATUS[0]}
      - name: Fakesign app
        run: |
          rm -rf archive.xcarchive/Products/Applications/emuThreeDS.app/Frameworks/emuThreeDS.framework/Frameworks/
          ldid -SemuThreeDS/Resources/tempEnt.plist archive.xcarchive/Products/Applications/emuThreeDS.app/emuThreeDS
      - name: Convert to IPA
        run: |
          mkdir Payload
          mkdir Payload/emuThreeDS.app
          cp -R archive.xcarchive/Products/Applications/SideStore.app/ Payload/SideStore.app/
          zip -r emuThreeDS.ipa Payload
      - name: Upload Artifact
        uses: actions/upload-artifact@v3.1.0
        with:
          name: emuThreeDS.ipa
          path: emuThreeDS.ipa
